# Generated by Django 4.2.2 on 2025-05-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("manager", "Менеджер")], default="user", max_length=20
            ),
        ),
    ]
