# Generated by Django 4.2.2 on 2025-06-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Имя"),
        ),
    ]
