# Generated by Django 4.2.2 on 2025-06-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, help_text="Введите имя", max_length=150, null=True, verbose_name="Имя"),
        ),
    ]
