# Generated by Django 4.2.2 on 2025-06-04 09:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name="Страна"),
        ),
    ]
