# Generated by Django 4.2.2 on 2025-03-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="editing",
            field=models.BooleanField(default=False),
        ),
    ]
