# Generated by Django 4.2.2 on 2025-03-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_client_editing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Оставьте комментарий о получателе", null=True, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                help_text="Введите email получателя", max_length=254, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(help_text="Введите ФИО получателя", max_length=200, verbose_name="Ф. И. О."),
        ),
    ]
