# Generated by Django 4.2.2 on 2025-03-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_client_comment_alter_client_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="end_time",
            new_name="end_datetime",
        ),
        migrations.RenameField(
            model_name="mailing",
            old_name="start_time",
            new_name="start_datetime",
        ),
        migrations.RemoveField(
            model_name="message",
            name="body",
        ),
        migrations.RemoveField(
            model_name="message",
            name="subject",
        ),
        migrations.AddField(
            model_name="message",
            name="text_message",
            field=models.TextField(default="", verbose_name="Сообщение"),
        ),
        migrations.AddField(
            model_name="message",
            name="topic_message",
            field=models.CharField(default="", max_length=200, verbose_name="Тема сообщения"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(default="Создана", max_length=20, verbose_name="Статус"),
        ),
    ]
