# Generated by Django 4.2.2 on 2025-03-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_rename_end_time_mailing_end_datetime_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attempt",
            options={"verbose_name": "Статус рассылки", "verbose_name_plural": "Статусы рассылок"},
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Получатель", "verbose_name_plural": "Получатели"},
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
    ]
