# Generated by Django 4.2.2 on 2025-03-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_alter_attempt_options_alter_client_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="clients",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="message",
        ),
        migrations.DeleteModel(
            name="Attempt",
        ),
        migrations.DeleteModel(
            name="Mailing",
        ),
    ]
