# Generated by Django 4.2.2 on 2025-03-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_mailing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="end_datetime",
        ),
        migrations.AddField(
            model_name="mailing",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата окончания рассылки"),
        ),
        migrations.AddField(
            model_name="mailing",
            name="repeat",
            field=models.CharField(
                choices=[
                    ("once", "Один раз"),
                    ("daily", "Ежедневно"),
                    ("weekly", "1 раз в неделю"),
                    ("monthly", "1 раз в месяц"),
                    ("yearly", "1 раз в год"),
                ],
                default="once",
                max_length=20,
                verbose_name="Повторяемость",
            ),
        ),
    ]
