# Generated by Django 4.2.2 on 2025-03-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0009_remove_mailing_end_datetime_mailing_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="end_date",
        ),
        migrations.AddField(
            model_name="mailing",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата окончания рассылки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="repeat",
            field=models.CharField(
                choices=[
                    ("once", "Один раз"),
                    ("daily", "Ежедневно"),
                    ("weekly", "1 раз в неделю"),
                    ("monthly", "1 раз в месяц"),
                    ("yearly", "1 раз в год"),
                ],
                default="once",
                max_length=20,
                verbose_name="Периодичность",
            ),
        ),
    ]
