# Generated by Django 4.2.2 on 2025-05-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0013_fill_user_field"),
    ]

    operations = []
