# Generated by Django 5.1.4 on 2025-02-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Ф.И.О."),
        ),
    ]
