# Generated by Django 5.1.4 on 2025-01-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_preview_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="preview_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog/images/"),
        ),
    ]
