# Generated by Django 4.2.2 on 2025-02-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blogpost_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={},
        ),
    ]
