# Generated by Django 4.2.2 on 2025-02-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_blogpost_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
    ]
