# Generated by Django 4.2.2 on 2025-02-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blogpost_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "permissions": [
                    ("can_edit_content", "Can edit content"),
                    ("can_edit_is_published", "Can edit is published"),
                ],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
